build:
	protoc --proto_path=. --go_out=proto/consignment/ --micro_out=./ \
    		proto/consignment/consignment.proto
#	protoc -I . --go_out=./proto/consignment \
#	  ./proto/consignment/consignment.proto
#	protoc 	--go_out=./proto/consignment   \
#		--go-grpc_opt=require_unimplemented_servers=false \
#		--go-grpc_out=./proto/consignment \
#	  ./proto/consignment/consignment.proto


